sauce_labs:
  username: farooq
  access_key: a2280004-36fd-4a44-ae1a-209696270d5e

developer_site:
  base: https://developer-temp-staging.idmeinc.net
  user: farooq@id.me

marketplace:
  landing_page: https://marketplace-staging.idmeinc.net/shop
  base: https://marketplace-staging.idmeinc.net/
  existing_user: test@troopswap.com

hlp:
  base: https://hosted-pages-staging.idmeinc.net
  ungated_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-preview-ungated-page
  gated_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-live-gated-page
  document_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-live-document-page
  promocode_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-live-promocode-page  
  # user: farooq@id.me
  # password: idmeadmin
  partner_number: 1

idp:
  base: https://idp-staging.idmeinc.net

oauth_tester:
  base: https://oauth-tester-staging.idmeinc.net
  general: farooq@id.me
  general2: farooq+1@id.me
  general3: farooq+2@id.me
  unverified: farooq+noverifications@id.me
  student: farooq+student@id.me
  teacher: farooq+teacher@id.me
  police: farooq+police@id.me
  firefighter: farooq+firefighter@id.me
  emt: farooq+emt@id.me
  usaa: farooq+usaa@id.me
  scra: farooq+scra@id.me
  loa1: farooq+loa1@id.me
  loa2: farooq+loa2@id.me
  loa3: farooq+loa3@id.me
  unconfirmed_email: farooq+unconfirmed_email@id.me

idme_admin:
  base: https://admin-staging.idmeinc.net
  user: farooq@id.me
  password: troopidadmin

general_password: Password123
weak_password: Password1
wrong_unlock_code: 123456
nonexistant_email: fake_email@id.me

oauth_logout:
  base: https://oauth-tester-staging.idmeinc.net/oauths/6/logout        

loa:
  sp1: https://sp1.idmeinc.net/
  sp2: https://sp2.idmeinc.net/
  sp3: https://sp3.idmeinc.net/

iva:
  base: https://verify-staging.idmeinc.net

destination:
  base: https://marketplace-staging.idmeinc.net/home

mp_users:
  base: https://marketplace-users-staging.idmeinc.net
  basic: test+basic@id.me
  basic_uid: 7371fb3356d7a3d01026
  preferred: test+preferred@id.me #test+c@id.me
  preferred_uid: d7e81e6cf5dc20e21025
  premium: test+premium@id.me
  premium_uid: 363e2633e104eb951023
  vip: test+be2@id.me
  vip_uid: eb1f9278afe5954d911

offers:
  base: https://offers-staging.idmeinc.net

offers_cms:
  base: https://offers-cms-staging.idmeinc.net/
  user: kseniia@id.me
  password: offerscmsadmin
  
mp_admin:
  email: admin@viget.com
  password: password1234
  
authority:
  base: https://authority-staging.idmeinc.net
  user: farooq+1@id.me
  password: idmeadmin