source "https://rubygems.org"

gem "rspec"
gem "thor"
gem "selenium-webdriver", "~> 2.53.0"
gem "rspec-expectations"
gem "gherkin"
gem "allure-cucumber"
gem "allure-ruby-adaptor-api"
gem "data_magic"
gem "fig_newton"
gem "headless"
gem "faker"
gem "pry-rails"
gem "pry"
gem "phantomjs"
gem "cucumber_statistics"
gem "parallel_tests"
gem "capybara"
gem "cucumber"
gem "rubocop"
gem "oauth2"
gem "httparty"
