# Local settings
authority:
 userid: testdev@id.me
 password: Password123

oauth:
  client_id     : cf3fbeb9d6c01cf47813d9bd1939b64f
  client_secret : i794df75d6424cc0b01f7ec06669da4b1
  idp_endpoint  : http://api.idme.dev
  redirect_uri  : http://testdrive.idme.dev
  general_password: Changeme123
  weak_password: Password1
  unverified: farooq+noverifications@id.me
  nonexistent: fake_email@id.me
  valid: farooq@id.me
  valid1: farooq+1@id.me
  valid2: farooq+2@id.me
  wrong_unlock_code: 123456
  loa1: farooq+loa1@id.me
  loa2: farooq+loa2@id.me
  loa3: farooq+loa3@id.me
  facebook_user: qnkuwmb_sadanberg_1446693931@tfbnw.net
  facebook_pw: facebooktest
  google_user: idme.qa.automation@gmail.com
  google_pw: $taRbuck$
  linkedin_user: bruce.wayne_test@yahoo.com
  linkedin_pw: PassWord12345
  paypal_user: test@id.me
  paypal_pw: testtest
  twitter_user:
  twitter_pw:
  experian_user: Erin Rashid
  policy:
    au10tix_light     : http://idmanagement.gov/ns/assurance/loa/3
    developer         : developer
    farooq            : farooq
    government        : government
    ficam_loa_1       : http://idmanagement.gov/ns/assurance/loa/1
    ficam_loa_2       : http://idmanagement.gov/ns/assurance/loa/2
    ficam_loa_3       : http://idmanagement.gov/ns/assurance/loa/3
    shop              : shop
    shop_edit         : shop_edit
    military          : military
    military_enforced : military-enforced
    military_scra     : military_scra
    payfone           : payfone
    responder         : responder
    student           : student
    teacher           : teacher
    wallet            : wallet
    general_password  : Password123

admin:
  base_url: http://admin.idme.dev
  user_quick_search: http://admin.idme.dev/searches
  api_username: idme
  api_password: idme
  users_endpoint: http://admin.idme.dev/api/users

support_tool:
  base_url: http://support.idme.dev
  homepage:
    url: http://support.idme.dev

idp:
  base_url: http://api.idme.dev
  new_session_url: http://api.idme.dev/session/new
  new_registration_url: http://api.idme.dev/registration/new

shop:
  shop_homepage: http://marketplace.idme.dev/
  cashback_purchases_homepage: http://marketplace.idme.dev/cash-back/purchases
  user_cashback_profile_url: http://marketplace.idme.dev/cash-back
  demographic_survey: http://marketplace.idme.dev/cash-back/survey/new
  invite_store: http://marketplace.idme.dev/cash-back/store-suggestions/new
  email_invitation_providers: http://marketplace.idme.dev/invitation-providers/new
  email_batch_invitations: http://marketplace.idme.dev/batch-invitations/new
  refer_friend_email: rich.purnell.rocketman@gmail.com, test+be2@id.me, eddie.park.tester@gmail.com
  refer_25_friends_email: <%= 25.times.map {|n| "test#{n}@id.me"}.join(",") %>
  user_settings_homepage: http://marketplace.idme.dev/profile/edit
  user_fname: Jack
  user_lname: Sparrow
  user_account_edit: http://marketplace.idme.dev/account/edit
  new_password: JollyRoger123
  group_affiliations_page: http://marketplace.idme.dev/cash-back/group-affiliations
  merchant_page: http://marketplace.idme.dev/stores/175-fanatics
  merchant_review_text: Review for Fanatics By William Wallace on July 05, 2016 I just got a discount at Fanatics and earned $6.60 in cash back.
  stores_index_page: http://marketplace.idme.dev/stores
  offers_index_page: http://marketplace.idme.dev/offers
  offers_promo_code_index_page: http://marketplace.idme.dev/offers?type=code
  offers_coupon_index_page: http://marketplace.idme.dev/offers?type=coupon

shop_admin:
  base: http://marketplace.idme.dev/admin
  offers: http://marketplace.idme.dev/admin/offers
  categories: http://marketplace.idme.dev/admin/categories
  stores:
    base_url: http://marketplace.idme.dev/admin/stores
  email_generator: http://marketplace.idme.dev/admin/email_templates

wallet:
  homepage:
    url: http://wallet.idme.dev/
    social_federation_url: http://wallet.idme.dev/#!
    title: One Identity. One Wallet. | ID.me
  dashboard: http://wallet.idme.dev/dashboard
  settings: http://wallet.idme.dev/settings
  myids: http://wallet.idme.dev/ids
  activity: http://wallet.idme.dev/activity
  shop: http://marketplace.idme.dev/
