partners:
  user:     tony.chung+test@id.me
  password: Password123
  fanatics: http://www.fanatics.com/NFL_New_England_Patriots_Jerseys/Tom_Brady_New_England_Patriots_Nike_Game_Jersey_-_Navy_Blue_Silver
  nfl_shop: https://www.nflshop.com/catalog/product/Mens_Washington_Redskins_Ryan_Kerrigan_Nike_Burgundy_Game_Jersey
