sauce_labs:
  username: farooq
  access_key: a2280004-36fd-4a44-ae1a-209696270d5e

partners:
  user:     tony.chung+test@id.me
  password: Password123
  fanatics: http://www.fanatics.com/NFL_New_England_Patriots_Jerseys/Tom_Brady_New_England_Patriots_Nike_Game_Jersey_-_Navy_Blue_Silver
  nfl_shop: https://www.nflshop.com/catalog/product/Mens_Washington_Redskins_Ryan_Kerrigan_Nike_Burgundy_Game_Jersey

marketplace:
  base: https://www.id.me/
  landing_page: https://id.me/shop

registration:
  base: https://api.id.me

idp:
  base: https://api.id.me

idme_admin:
  base: https://admin.idmeinc.net
  user: farooq@id.me
  password: 2XsmilEjFg9S

general_password: Password123
weak_password: Password1

marketplace_existing_user: test@troopswap.com

# hlp:
#   base: https://hosted-pages.id.me
#   user: kseniia@id.me
#   password: idmeadmin
#   partner_number: 49

hlp:
  base: https://hosted-pages-staging.idmeinc.net
  ungated_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-preview-ungated-page
  gated_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-live-gated-page
  document_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-live-document-page
  promocode_live: https://hosted-pages-staging.idmeinc.net/sam-s-club-live-promocode-page

  # user: farooq@id.me
  # password: idmeadmin
  partner_number: 1

oauth_tester:
  base: https://oauth-tester-staging.idmeinc.net

loa1:
  base: https://sp1.idmeinc.net/

loa2:
  base: https://sp2.idmeinc.net/

loa3:
  base: https://sp3.idmeinc.net/

iva:
  base: https://verify-staging.idmeinc.net

destination:
  base: https://id.me/home

mp_users:
  base:

offers:
  base: https://offers-01.idmeinc.net

offers_cms:
  base: https://offers-cms.idmeinc.net/

authority:
  base: https://authority-staging.idmeinc.net
  user: farooq@id.me
  password: idmeadmin
