api_dummy_site:
 main_url: https://jsonplaceholder.typicode.com
 users_url: https://jsonplaceholder.typicode.com/users/
 users_one_url: https://jsonplaceholder.typicode.com/users/1

ultimate_qa_site:
  url: https://ultimateqa.com/simple-html-elements-for-automation/