sauce_labs:
  username: farooq
  access_key: a2280004-36fd-4a44-ae1a-209696270d5e

partners:
  user:     tony.chung+test@id.me
  password: Password123
  fanatics: http://www.fanatics.com/partnerid/14301/NFL_New_England_Patriots
  nfl_shop: https://www.nflshop.com/catalog/product/Mens_Washington_Redskins_Ryan_Kerrigan_Nike_Burgundy_Game_Jersey
  fansedge: http://www.fansedge.com/New_England_Patriots_Merchandise/Nike_Tom_Brady_New_England_Patriots_Navy_Blue_Silver_Game_Jersey
  nhl_shop: http://shop.nhl.com/Boston_Bruins_Jerseys/Mens_Boston_Bruins_Reebok_Black_2016_Winter_Classic_Premier_Jersey
