sauce_labs:
  username: farooq
  access_key: a2280004-36fd-4a44-ae1a-209696270d5e

partners:
  user:     tony.chung+test@id.me
  password: Password123
  fanatics: http://www.fanatics.com/NFL_Denver_Broncos_Mens/Peyton_Manning_Denver_Broncos_Nike_Super_Bowl_50_Game_Jersey_-_Orange
  fanatics_discount: "A discount of 10% and free shipping was successfully applied to your order."
  nfl_shop: https://www.nflshop.com/catalog/product/Mens_Washington_Redskins_Ryan_Kerrigan_Nike_Burgundy_Game_Jersey
  fansedge: http://www.fansedge.com/New_England_Patriots_Merchandise/Nike_Tom_Brady_New_England_Patriots_Navy_Blue_Silver_Game_Jersey
  fansedge_discount: "A discount of 10% and free shipping was successfully applied to your order."
  fansedge_discount_amount: "-$10.00"
  ny_giants: http://shop.giants.com/New_York_Giants_Jerseys/Mens_New_York_Giants_Eli_Manning_Nike_Royal_Blue_Game_Jersey
  eagles: http://store.philadelphiaeagles.com/Philadelphia_Eagles_Mens_Jerseys/Mens_Philadelphia_Eagles_Brian_Dawkins_Nike_Midnight_Green_Game_Jersey
  seahawks: http://proshop.seahawks.com/Seattle_Seahawks_Mens_Jerseys/Mens_Seattle_Seahawks_Russell_Wilson_Nike_College_Navy_Game_Jersey
  nba_shop: http://store.nba.com/Boston_Celtics_Mens/Mens_Boston_Celtics_Larry_Bird_adidas_Kelly_Green_Hardwood_Classics_Swingman_Jersey
  nhl_shop: http://shop.nhl.com/Boston_Bruins_Jerseys/Mens_Boston_Bruins_Reebok_Black_2016_Winter_Classic_Premier_Jersey
  az_cardinals: http://shop.azcardinals.com/Arizona_Cardinals_Mens_Jerseys/Mens_Arizona_Cardinals_Tyrann_Mathieu_Nike_Cardinal_Game_Jersey
  nascar: http://store.nascar.com/Mens_Jackets/Mens_Dale_Earnhardt_Jr._Black_Nationwide_Insurance_Uniform_Twill_Jacket
  mlb_shop: http://shop.mlb.com/Baltimore_Orioles_Gear
  mlb_shop_discount: "A discount of 15% was successfully applied to your order."
  mlb_shop_discount_amount: "-$18.00"
  caesars_hotels: https://www.caesars.com
  seaworld_url: http://seaworldparks.com/seaworld-orlando/waves-of-honor/veterans
  underarmour_url: https://www.underarmour.com/en-us/men-s-ua-streaker-run-v-neck-t-shirt/pid1276515-016
  underarmour_item_subtotal: "Items: $34.99"
  underarmour_discount_amount: "Promotion: -$3.50"
  mlb_tv_subscription_page: http://mlb.mlb.com/mlb/subscriptions
  mlb_tv_yearly_subscription: "109.99 / Yearly"
  carhartt_homepage: http://www.carhartt.com/products/carhartt-men-outerwear/Shoreline-Jacket-J162
  ford_user: eddie.park.tester@gmail.com
  ford_password: Password123
