oauth_tester:
 general_password: Password123
 weak_password: Password1
 unverified: farooq+noverifications@id.me
 nonexistent: fake_email@id.me
 valid: farooq@id.me
 valid1: farooq+1@id.me
 valid2: farooq+2@id.me
 wrong_unlock_code: 123456
 loa1: farooq+loa1@id.me
 loa2: farooq+loa2@id.me
 loa3: farooq+loa3@id.me
 facebook_user: Karen Sadanberg
 google_user:
 linkedin_user:
 twitter_user:
 experian_user: Erin Rashid

authority:
 userid: farooq+1@id.me
 password: idmeadmin

oauth:
  client_id     : 8e7d94dd2114a4ba54b8ef7950446aaa
  client_secret : ff5a9ef3aeb9a98ab49ee42662b8f58e
  idp_endpoint  : https://api-staging.idmeinc.net
  redirect_uri  : https://oauth-tester-staging.idmeinc.net
  weak_password: Password1
  unverified: farooq+noverifications@id.me
  nonexistent: fake_email@id.me
  valid: farooq@id.me
  valid1: farooq+1@id.me
  valid2: farooq+2@id.me
  wrong_unlock_code: 123456
  loa1: farooq+loa1@id.me
  loa2: farooq+loa2@id.me
  loa3: farooq+loa3@id.me
  facebook_user: Karen Sadanberg
  google_user:
  linkedin_user:
  twitter_user:
  experian_user: Erin Rashid
  policy:
    developer         : developer
    farooq            : farooq
    government        : government
    ficam_loa_1       : http://idmanagement.gov/ns/assurance/loa/1
    ficam_loa_2       : http://idmanagement.gov/ns/assurance/loa/2
    ficam_loa_3       : http://idmanagement.gov/ns/assurance/loa/3
    marketplace       : marketplace
    marketplace_edit  : marketplace_edit
    military          : military
    military_enforced : military-enforced
    military_scra     : military_scra
    payfone           : payfone
    responder         : responder
    student           : student
    teacher           : teacher
    wallet            : wallet
    general_password: Password123

mp_users:
  mp_homepage: https://marketplace-users-staging.idmeinc.net
  basic: test+basic@id.me
  basic_uid: 7371fb3356d7a3d01026
  preferred: test+preferred@id.me #test+c@id.me
  preferred_uid: d7e81e6cf5dc20e21025
  premium: test+premium@id.me
  premium_uid: 363e2633e104eb951023
  vip: test+24@id.me
  general_password: Password123
  vip_uid: 551dee265b914ad2a0af7eebf872d502

marketplace:
  shop_homepage: https://marketplace-staging.idmeinc.net/shop
  cashback_purchases_homepage: https://marketplace-staging.idmeinc.net/cash-back/purchases
  user_cashback_profile_url: https://marketplace-staging.idmeinc.net/cash-back
  demographic_survey: https://marketplace-staging.idmeinc.net/cash-back/survey/new
  invite_store: https://marketplace-staging.idmeinc.net/cash-back/store-suggestions/new
  email_invitation_providers: https://marketplace-staging.idmeinc.net/invitation-providers/new
  email_batch_invitations: https://marketplace-staging.idmeinc.net/batch-invitations/new
  refer_friend_email: rich.purnell.rocketman@gmail.com, test+be2@id.me, eddie.park.tester@gmail.com
  refer_25_friends_email: <%= 25.times.map {|n| "test#{n}@id.me"}.join(",") %>
  user_settings_homepage: https://marketplace-staging.idmeinc.net/profile/edit
  user_fname: Jack
  user_lname: Sparrow
  user_account_edit: https://marketplace-staging.idmeinc.net/account/edit
  new_password: JollyRoger123
  saved_offers_page: https://marketplace-staging.idmeinc.net/saved_offers

social_network:
  facebook_email: eddie.park.tester@gmail.com
  facebook_password: Password123123
  twitter_email: eddie.park.tester@gmail.com
  twitter_password: Password123123
  linkedin_email: eddie.park.tester@gmail.com
  linkedin_password: Password123123

admin:
  base_url: https://admin-staging.idmeinc.net

idp:
  base_url: https://api-staging.idmeinc.net
  new_session_url: https://api-staging.idmeinc.net/session/new

hlp:
  homepage: https://hosted-pages-staging.idmeinc.net/admin/partners/1/pages
  partner_number: 1

hlp_page_test_data:
  body_copy: Mauris eget ornare enim. Quisque sagittis velit ut dui mollis eleifend. Quisque vel interdum risus. Praesent sit amet cursus ex. Mauris suscipit posuere nibh. Phasellus maximus bibendum lectus eget auctor. Curabitur semper placerat lacus ac tincidunt.
  ungated_page:
    name: Sam's Club Military Special Ungated Page
    page_redirect_url: https://www.google.com
    duplicate_page_name: Sam's Club Military Special Ungated Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-ungated-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-ungated-page
    live_page_title: Sam's Club Military Special Ungated Page - ID.me
  document_page:
    name: Sam's Club Military Special Document Page
    duplicate_page_name: Sam's Club Military Special Document Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-document-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-document-page
    live_page_title: Sam's Club Military Special Document Page - ID.me
  gated_page:
    name: Sam's Club Military Special Gated Page
    duplicate_page_name: Sam's Club Military Special Gated Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-gated-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-gated-page
    live_page_title: Sam's Club Military Special Gated Page - ID.me
  promo_code_page:
    name: Sam's Club Military Special Promo Code Page
    header: Honored to Serve Those Who Serve
    subheader: Join or renew and get up to a $25 Sam's Club Gift Card with promo code
    number_of_codes_per_user: 1
    duplicate_page_name: Sam's Club Military Special Promo Code Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-promo-code-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-promo-code-page
    live_page_title: Sam's Club Military Special Promo Code Page - ID.me
  wufoo_code_page:
    name: Sam's Club Military Special Wufoo Page
    duplicate_page_name: Sam's Club Military Special Wufoo Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-wufoo-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-wufoo-page
    live_page_title: Sam's Club Military Special Wufoo Page - ID.me
