sauce_labs:
 username: farooq
 access_key: a2280004-36fd-4a44-ae1a-209696270d5e

authority:
 userid: farooq+1@id.me
 password: IDmeadmin3

oauth:
  client_id     : 19bc32958f52e7dd8fd7b5f2eaa42718
  client_secret : 905cb39e22d413a8b4a74a2544ae8bf8
  idp_endpoint  : https://api-staging.idmeinc.net
  redirect_uri  : https://test-drive-staging.idmeinc.net
  general_password: Changeme123
  weak_password: Password1
  unverified: farooq+noverifications@id.me
  nonexistent: fake_email@id.me
  valid : password_test@id.me
  valid1: password_test+1@id.me
  valid2: password_test+2@id.me
  wrong_unlock_code: 123456
  loa1: farooq+loa1@id.me
  loa2: farooq+loa2@id.me
  loa3: farooq+loa3@id.me
  facebook_user: qnkuwmb_sadanberg_1446693931@tfbnw.net
  facebook_pw: facebooktest
  google_user: idme.qa.automation@gmail.com
  google_pw: $taRbuck$
  linkedin_user: bruce.wayne_test@yahoo.com
  linkedin_pw: PassWord12345
  paypal_user: test@id.me
  paypal_pw: testtest
  twitter_user:
  twitter_pw:
  experian_user: Erin Rashid
  policy:
    au10tix_light     : au10tix-light
    developer         : developer
    farooq            : farooq
    government        : government
    ficam_loa_1       : http://idmanagement.gov/ns/assurance/loa/1
    ficam_loa_2       : http://idmanagement.gov/ns/assurance/loa/2
    ficam_loa_3       : http://idmanagement.gov/ns/assurance/loa/3
    shop              : shop
    shop_edit         : shop_edit
    military          : military
    military_enforced : military-enforced
    military_scra     : military_scra
    payfone           : payfone
    responder         : responder
    student           : student
    teacher           : teacher
    wallet            : wallet
    general_password  : Password123

direct_api:
  storage_enabled:
    client_id     : a8a8ab3174466f3bbecca8c546439796
    client_secret : fb77531f394fbb3495b724f7215120c5
    header_auth   : Basic YThhOGFiMzE3NDQ2NmYzYmJlY2NhOGM1NDY0Mzk3OTY6ZmI3NzUzMWYzOTRmYmIzNDk1YjcyNGY3MjE1MTIwYzU=
  storage_disabled:
    client_id     : 42b41c3cc7d52b5f7ed68c57de8f8659
    client_secret : 76f1e72aa8b0859d1db7382f111b3c00
    header_auth   : Basic NDJiNDFjM2NjN2Q1MmI1ZjdlZDY4YzU3ZGU4Zjg2NTk6NzZmMWU3MmFhOGIwODU5ZDFkYjczODJmMTExYjNjMDA=
  valid_attributes:
    first_name : john
    last_name  : jones
    birth_date : "1989-05-25"
    ssn        : 000149876
  invalid_attributes:
    first_name : star
    last_name  : fire
    birth_date : "1989-08-28"
    ssn        : 000678914

shop_users:
  shop_homepage: https://shop-users-staging.idmeinc.net
  basic: test+basic@id.me
  basic_uid: 7371fb3356d7a3d01026
  preferred: test+preferred@id.me #test+c@id.me
  preferred_uid: d7e81e6cf5dc20e21025
  premium: test+premium@id.me
  premium_uid: 363e2633e104eb951023
  military: test+24@id.me
  general_password: Password1234567
  incorrect_password: 2legit2quit
  vip_uid: 551dee265b914ad2a0af7eebf872d502

shop:
  shop_homepage: https://shop-staging.idmeinc.net/
  cashback_purchases_homepage: https://shop-staging.idmeinc.net/cash-back/purchases
  user_cashback_profile_url: https://shop-staging.idmeinc.net/cash-back
  demographic_survey: https://shop-staging.idmeinc.net/cash-back/survey/new
  invite_store: https://shop-staging.idmeinc.net/cash-back/store-suggestions/new
  email_invitation_providers: https://shop-staging.idmeinc.net/invitation-providers/new
  email_batch_invitations: https://shop-staging.idmeinc.net/batch-invitations/new
  refer_friend_email: rich.purnell.rocketman@gmail.com, test+be2@id.me, eddie.park.tester@gmail.com
  refer_25_friends_email: <%= 25.times.map {|n| "test#{n}@id.me"}.join(",") %>
  user_settings_homepage: https://shop-staging.idmeinc.net/profile/edit
  user_fname: Jack
  user_lname: Sparrow
  user_account_edit: https://shop-staging.idmeinc.net/account/edit
  new_password: JollyRoger123
  group_affiliations_page: https://shop-staging.idmeinc.net/cash-back/group-affiliations
  merchant_page: https://shop-staging.idmeinc.net/stores/175-fanatics
  merchant_review_text: Review for Fanatics By William Wallace on July 05, 2016 I just got a discount at Fanatics and earned $6.60 in cash back.
  stores_index_page: https://shop-staging.idmeinc.net/stores
  offers_index_page: https://shop-staging.idmeinc.net/offers
  offers_promo_code_index_page: https://shop-staging.idmeinc.net/offers?type=code
  offers_coupon_index_page: https://shop-staging.idmeinc.net/offers?type=coupon

social_network:
  facebook_email: eddie.park.tester@gmail.com
  facebook_password: Password123123
  twitter_email: eddie.park.tester@gmail.com
  twitter_password: Password123123
  linkedin_email: eddie.park.tester@gmail.com
  linkedin_password: Password123123

admin:
  base_url: https://admin-staging.idmeinc.net
  user_quick_search: https://admin-staging.idmeinc.net/searches
  api_username: revelator
  api_password: 8419400ef9b3b5f468caba8bbade41aa
  users_endpoint: https://admin-staging.idmeinc.net/api/users

support_tool:
  base_url: https://support-staging.idmeinc.net/
  waiting_attempts: https://support-staging.idmeinc.net/verification/attempts?waiting=true

idp:
  base_url: https://api-staging.idmeinc.net
  new_session_url: https://api-staging.idmeinc.net/session/new
  new_registration_url: https://api-staging.idmeinc.net/registration/new
hlp:
  homepage: https://hosted-pages-staging.idmeinc.net/admin/partners/26/pages
  partner_number: 26

hlp_page_test_data:
  body_copy: Mauris eget ornare enim. Quisque sagittis velit ut dui mollis eleifend. Quisque vel interdum risus. Praesent sit amet cursus ex. Mauris suscipit posuere nibh. Phasellus maximus bibendum lectus eget auctor. Curabitur semper placerat lacus ac tincidunt.
  document_page:
    name: Sam's Club Military Special Document Page
    duplicate_page_name: Sam's Club Military Special Document Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-document-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-document-page
    live_page_title: ID.me - Sam's Club Military Special Document Page
  gated_page:
    name: Sam's Club Military Gated Page
    duplicate_page_name: Sam's Club Military Gated Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-gated-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-gated-page
    live_page_title: ID.me - Sam's Club Military Gated Page
  promo_code_page:
    name: Sam's Club Military Special Promo Code Page
    header: Honored to Serve Those Who Serve
    subheader: Join or renew and get up to a $25 Sam's Club Gift Card with promo code
    number_of_codes_per_user: 1
    duplicate_page_name: Sam's Club Military Special Promo Code Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-promo-code-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-promo-code-page
    live_page_title: ID.me - Sam's Club Military Special Promo Code Page
  wufoo_code_page:
    name: Sam's Club Military Special Wufoo Page
    duplicate_page_name: Sam's Club Military Special Wufoo Page copy
    preview_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-wufoo-page?preview=true
    live_page_url: https://hosted-pages-staging.idmeinc.net/sam-s-club-sam-s-club-military-special-wufoo-page
    live_page_title: ID.me - Sam's Club Military Special Wufoo Page

offer_cms:
  base_url: https://offers-cms-staging.idmeinc.net/

wallet:
  homepage:
    url: https://wallet-staging.idmeinc.net/
    social_federation_url: https://wallet-staging.idmeinc.net/#!
    title: One Identity. One Wallet. | ID.me
  dashboard: https://wallet-staging.idmeinc.net/dashboard
  settings: https://wallet-staging.idmeinc.net/settings
  myids: https://wallet-staging.idmeinc.net/ids
  activity: https://wallet-staging.idmeinc.net/activity
  shop: https://shop-staging.idmeinc.net/

idme:
  about_page: https://wallet-staging.idmeinc.net/about
  business_page: https://business.id.me/

shop_admin:
  base: https://shop-staging.idmeinc.net/admin
  categories: https://shop-staging.idmeinc.net/admin/categories
  email_generator: https://shop-staging.idmeinc.net/admin/email_templates
  stores:
    base_url: https://shop-staging.idmeinc.net/admin/stores
    test_store: Test
  offers:
    url: https://shop-staging.idmeinc.net/admin/offers
    offer_merchant_id: 101377
    offer_affiliate_url: https://www.avantlink.com/123123
