oauth_tester:
 general_password: Password123
 weak_password: Password1
 unverified: farooq+noverifications@id.me
 nonexistent: fake_email@id.me
 valid: farooq@id.me
 valid1: farooq+1@id.me
 valid2: farooq+2@id.me
 wrong_unlock_code: 123456

authority:
 userid: farooq@id.me
 password: idmeadmin

mp_users:
  mp_homepage: https://marketplace-users-staging.idmeinc.net
  basic: test+basic@id.me
  basic_uid: 7371fb3356d7a3d01026
  preferred: test+preferred@id.me #test+c@id.me
  preferred_uid: d7e81e6cf5dc20e21025
  premium: test+premium@id.me
  premium_uid: 363e2633e104eb951023
  vip: test+24@id.me
  general_password: Password123
  vip_uid: 551dee265b914ad2a0af7eebf872d502

marketplace:
  shop_homepage: https://marketplace-staging.idmeinc.net/shop
  cashback_purchases_homepage: https://marketplace-staging.idmeinc.net/cash-back/purchases
  user_cashback_profile_url: https://marketplace-staging.idmeinc.net/cash-back
  demographic_survey: https://marketplace-staging.idmeinc.net/cash-back/survey/new
  invite_store: https://marketplace-staging.idmeinc.net/cash-back/store-suggestions/new
  email_invitation_providers: https://marketplace-staging.idmeinc.net/invitation-providers/new
  email_batch_invitations: https://marketplace-staging.idmeinc.net/batch-invitations/new
  refer_friend_email: rich.purnell.rocketman@gmail.com, test+be2@id.me, eddie.park.tester@gmail.com
  refer_25_friends_email: <%= 25.times.map {|n| "test#{n}@id.me"}.join(",") %>
social_network:
  facebook_email: eddie.park.tester@gmail.com
  facebook_password: Password123123
  twitter_email: eddie.park.tester@gmail.com
  twitter_password: Password123123
  linkedin_email: eddie.park.tester@gmail.com
  linkedin_password: Password123123

admin:
  base_url: https://admin-staging.idmeinc.net

idp:
  base_url: https://idp-staging.idmeinc.net
